name: terraform-lint
on:
  pull_request:
  push:
    branches: [ main, master ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.9.5 }
      - run: terraform init -backend=false
      - run: terraform fmt -check -recursive
      - run: terraform validate
